Repository novaDepto/Nova, pull requests merged in 2020-11, with the labels that each got.

#164 Fix Proceso para definir alcance
  Proceso-para-definir-el-alcance.md
Labels: Review Required

#166 Update: Política de Nova WoW
  Politica-de-Nova-WoW.md
Labels: Review Required

#169 Proceso de mejora continua
  Proceso-de-mejora-continua.md
Labels: Review Required

#168 Update: Política Nova Wow - Error de sintaxis
  Politica-de-Nova-WoW.md
Labels: Review Required

#167 Update Proceso-de-inicio-de-iteración.md
  Proceso-de-inicio-de-iteración.md
Labels: Requested Changes Fixed, Review Required

#183 Proceso de presentaciones
  Proceso-de-presentaciones.md
  _Sidebar.md
Labels: Review Required

#173 Línea base de la wiki
  Línea-base-de-la-wiki.md
Labels: Review Required

#182 Update Proceso-de-mejora-continua.md
  Proceso-de-mejora-continua.md
Labels: Requested Changes Fixed, Review Required

#177 Update Plantilla-de-proceso.md
  Plantilla-de-proceso.md
Labels: Commented, Review Required

#174 Update Politica-de-elementos-de-la-configuracion.md
  Politica-de-elementos-de-la-configuracion.md
Labels: Review Required

#178 Update Plantilla-de-política.md
  Plantilla-de-política.md
Labels: Commented, Review Required

#188 Guía de la Estrategia Técnica
  Guía-de-estrategia-técnica.md
Labels: Commented, Review Required

#190 Update Proceso-para-definir-el-alcance.md
  Proceso-para-definir-el-alcance.md
Labels: Review Required

#189 Update and rename Guía-para-Estimar.md to Guía-para-estimar.md
  Guía-para-Estimar.md
  Guía-para-estimar.md
Labels: Requested Changes Fixed, Review Required

#180 Update Proceso-para-institucionalizar-procesos-guías-y-políticas.md
  Proceso-para-institucionalizar-procesos-guías-y-políticas.md
Labels: Requested Changes Fixed, Review Required

#191 Proceso de inspección de componentes
  Proceso-de-inspección-de-componentes.md
  _Sidebar.md
Labels: Review Required

#193 Process Improvement Proposal: Links Testing
  .github/scripts/test_links.py
  .github/workflows/link_tests.yml
  CODEOWNERS
  Guía-para-identificar-procesos-guías-políticas.md
Labels: Review Required

#196 Docs/directoriocannis
  Directorio-de-archivos-del-departamento.md
Labels: Review Required

#176 Update Proceso-de-asignación-de-roles.md
  Proceso-de-asignación-de-roles.md
Labels: Changes Requested, Commented

#201 fix: Remover pasos y agregar detalle al proceso
  Proceso-para-generar-un-backlog.md
Labels: Review Required

#195 Update Proceso-de-acciones-correctivas.md
  Proceso-de-acciones-correctivas.md
Labels: Requested Changes Fixed, Review Required

#203 Create Guía_de_Exposición_Oral.md
  Guía_de_Exposición_Oral.md
Labels: Changes Requested

#204 agregar a la fase de seguimiento el proceso de acciones correctivas
  Proceso-para-junta-con-el-cliente.md
Labels: Review Required

#205 se agrega una fase de medición y en ella el proceso de gestión de mét…
  Proceso-para-generar-un-backlog.md
Labels: Review Required

#209 Esta es la buena de Guía de Exposición
  Guía-de-Exposición-Oral.md
Labels: Review Required

#210 Update _Sidebar.md
  _Sidebar.md
Labels: Review Required

#213 Update Proceso-de-validación.md
  Proceso-de-validación.md
Labels: Review Required

#208 Delete Guía_de_Exposición_Oral.md
  Guía_de_Exposición_Oral.md
Labels: Review Required

#214 fix: Remove "seguimiento" steps, add specificity
  Proceso-de-gestión-de-riesgos.md
Labels: Review Required

#216 Guía para identificar recursos del proyecto
  Guía-para-la-identificación-de-recursos-del-proyecto.md
Labels: Review Required

#211 Delete Cuestionario-de-Salud-Discord-Cheatsheet.md
  Cuestionario-de-Salud-Discord-Cheatsheet.md
  Línea-base-de-la-wiki.md
  _Sidebar.md
Labels: Requested Changes Fixed, Review Required

#212 Delete Proceso-de-mejora-de-procesos.md
  Línea-base-de-la-wiki.md
  Proceso-de-mejora-de-procesos.md
  Proceso-de-modificacion-de-linea-base.md
Labels: Requested Changes Fixed, Review Required

#198 Update and rename Proceso-Cierre-de-Iteracion.md to Proceso-de-cierre…
  Proceso-Cierre-de-Iteracion.md
  Proceso-de-cierre-de-iteración.md
  _Sidebar.md
Labels: Requested Changes Fixed, Review Required

#206 Create Proceso-de-Acompañamie-to-para-Competencia-Oral.md
  Proceso-de-acompañamiento-para-competencia-oral.md
Labels: Requested Changes Fixed, Review Required

#217 PIP Agregar actividad de justificación de cambios y gestión de cambios a plantillas
  Guía-para-institucionalizar-procesos-guías-políticas.md
  Proceso-para-institucionalizar-procesos-guías-y-políticas.md
Labels: Requested Changes Fixed

#219 Criterios para aceptar cambios a US
  Guía-de-petición-de-cambios-a-historias-de-usuario.md
Labels: Review Required

#220 PIP: Agregar criterios de aceptación para requisitos y cambios
  Proceso-de-gestión-de-cambios-a-historias-de-usuario.md
  Proceso-de-recolección-de-requisitos.md
Labels: Review Required

#223 Anadir guia inconsistencias a Proceso Validacion
  Proceso-de-validación.md
Labels: Review Required

#224 Update: Directorio Andrómeda
  Directorio-de-archivos-del-departamento.md
  _Sidebar.md
Labels: Review Required

#226 Update: Proceso de Mejora continua
  Proceso-de-mejora-continua.md
Labels: Review Required

#222 Anadir Guia de Inconsistencias, Proceso Inicio
  Proceso-de-inicio-de-iteración.md
Labels: Requested Changes Fixed, Review Required

#227 Desarrollo de historias de usuario
  Proceso-para-desarrollar-una-historia-de-usuario.md
  _Sidebar.md
Labels: Requested Changes Fixed, Review Required

#225 Se añade tiempo especifico para atender los pull requests
  Politica-de-Nova-WoW.md
Labels: Review Required

#228 Guía para identificar recursos
  Guía-para-la-identificación-de-recursos-del-proyecto.md
  _Sidebar.md
Labels: Review Required

#229 Identifica los recusos de un proyecto
  Proceso-para-definir-el-alcance.md
Labels: Review Required

#231 Update: Reporte de estado
  Proceso-de-reporte-de-estado.md
Labels: Review Required

#230 PIP: Mejora a la plantilla para log de defectos
  Guía-de-CMMI.md
Labels: Approved, Commented, Communication Required, Review Required

#234 mejora proceso daily meeting (agregar comunicar acuerdos con stakehol…
  Proceso-de-Daily-Meeting.md
Labels: Review Required, merge conflict

#232 Update: Proceso de cierre de iteración - Checar milestones
  Proceso-de-cierre-de-iteración.md
Labels: Commented, Review Required

#235 pip: Cambiar el proceso para que incluya mejor MA
  Proceso-de-cierre-de-iteración.md
  _Sidebar.md
Labels: Review Required

#240 PIP: Proceso de Gestión de Métricas
  Proceso-de-Gestión-de-Métricas.md
Labels: Review Required

#239 pip proceso plan involucramiento con stakeholder
  Proceso-para-plan-de-Involucramiento-de-Stakeholders.md
Labels: Review Required, enhancement

#237 Update Proceso-de-mejora-continua.md
  Proceso-de-mejora-continua.md
Labels: Review Required

#242 PIP: Se agregaron criterios para proveedor de requisitos y cambio el objetivo
  Proceso-de-recolección-de-requisitos.md
Labels: Commented, Review Required

#236 Guía de Creación de Métricas
  Guía-de-Creación-de-Métricas.md
  _Sidebar.md
Labels: Review Required

#238 Update Proceso-para-institucionalizar-procesos-guías-y-políticas.md
  Proceso-para-institucionalizar-procesos-guías-y-políticas.md
Labels: Review Required

#243 Update: Monitoreo de datos a cierre de iteración
  Proceso-de-cierre-de-iteración.md
Labels: Commented, Review Required

#247 Update: Se agrega sección de ambiente de trabajo para VAL al proceso …
  Proceso-para-definir-el-alcance.md
Labels: Review Required

#246 Update: Se agrega el área de VAL al proceso
  Proceso-de-recolección-de-requisitos.md
Labels: Review Required

#250 Delete Guía-de-asignación-de-roles.md
  Guía-de-asignación-de-roles.md
Labels: Review Required

#244 se agregó en fase de mantenimiento del plan proceso punto de REQM que…
  Proceso-de-Daily-Meeting.md
  Proceso-de-gestión-de-métricas.md
Labels: Commented, Review Required

#245 Guía de Validación y Verificación de productos
  Guía-de-validación-de-historias-de-usuario.md
  Guía-de-verificación-y-validación-de-productos.md
  Proceso-de-validación.md
  _Sidebar.md
Labels: Commented, Review Required

#253 Update and rename Proceso-de-inspección-de-componentes.md to Proceso-…
  Proceso-de-inspección-de-componentes.md
  Proceso-de-inspección.md
  _Sidebar.md
Labels: Commented, Review Required

#256 Update Guía-del-Team-Leader.md
  Guía-del-Team-Leader.md
Labels: Review Required

#257 Update Guía-de-Team-Member.md
  Guía-de-Team-Member.md
Labels: Review Required

#251 Guia/entorno verificacionv3
  Guía-de-entorno-de-verificación.md
Labels: Requested Changes Fixed, Review Required

#263 Actualizar Sidebar con links de guías de roles
  _Sidebar.md
Labels: Review Required

#259 Update Guía-del-Program-Manager.md
  Guía-del-Program-Manager.md
Labels: Review Required

#262 Update Proceso-de-Pair-Review.md
  Proceso-de-Pair-Review.md
Labels: Review Required

#261 Update Proceso-de-inspección.md
  Proceso-de-inspección.md
Labels: Review Required

#264 Corrección de errores que salieron en la verificación de insitucional…
  Guía-de-Exposición-Oral.md
  Guía-de-estrategia-técnica.md
  Guía-para-la-identificación-de-recursos-del-proyecto.md
  Proceso-de-acompañamiento-para-competencia-oral.md
  Proceso-de-presentaciones.md
  _Sidebar.md
Labels: Requested Changes Fixed, Review Required

#268 Agregar pip: proceso para desarrollar historias de usuario Andrómeda
  Proceso-de-desarrollo-de-historias-de-usuario-Andrómeda.md
  _Sidebar.md
Labels: Requested Changes Fixed, Review Required

#254 Update and rename Guía-del-product-owner.md to Guía-del-Product-Owner.md
  Guía-del-Product-Owner.md
  Guía-del-product-owner.md
Labels: Requested Changes Fixed, Review Required, help wanted

#271 Sidebar_PO
  _Sidebar.md
Labels: Requested Changes Fixed, Review Required

#272 Se agregó que el PO hace la validación, se especifica que productos s…
  Proceso-de-validación.md
Labels: merge conflict

#255 Deteccion de necesidades/acuerdo con socio
  Proceso-de-recolección-de-requisitos.md
Labels: Requested Changes Fixed, Review Required

#274 Guía de Manuales
  Guía-de-Manuales.md
  _Sidebar.md
Labels: Requested Changes Fixed, Review Required, enhancement

#275 Guía del AO corregida
  Guía-del-architect-owner.md
  Política-sobre-roles-y-responsabilidades.md
  _Sidebar.md
Labels: Review Required

#276 Update: condensar proceso de inicio de iteración
  Proceso-de-inicio-de-iteración.md
Labels: Review Required

#269 fix links en el proceso
  Proceso-de-desarrollo-de-historias-de-usuario-Andrómeda.md
Labels: Commented, Review Required

#277 actualizar proceso de validación
  Proceso-de-validación.md
Labels: Requested Changes Fixed, Review Required

#280 Proceso de desarrollo de historias de usuario del proyecto cannis
  Proceso-para-desarrollar-una-historia-de-usuario-Cannis-Majoris.md
  _Sidebar.md
Labels: Approved, merge conflict
