Repository novaDepto/Nova, pull requests merged in 2020-10, with the labels that each got.

#41 [GUI11] Guía de versionado
  [GUI11]-Guía-de-versionado.md
  _Sidebar.md
Labels: Communication Required, Review Required

#38 [GUI10] Guía de manejo de configuración
  [GUI10]-Guía-de-manejo-de-configuración.md
  _Sidebar.md
Labels: Communication Required, Review Required

#39 Añadir paso para agregar IDs a los procesos
  [PRO01]-Proceso-para-definir-un-proceso.md
  _Sidebar.md
Labels: Communication Required, Review Required

#40 se borró el título, porque aparecía 2 veces
  Guía para identificar procesos, guías y_o políticas.md
Labels: Approved, Review Required

#20 Guía para definir un WBS
  Guía-para-definir-un-WBS.md
  _Sidebar.md
Labels: Requested Changes Fixed, Review Required

#44 Añadir plantillas de política y proceso
  Guía para identificar procesos, guías y_o políticas.md
  Plantilla-de-política.md
  Plantilla-de-proceso.md
  Política-de-juntas-de-desempeño.md
  Política-de-juntas-de-seguimiento-personal-(JSP).md
  _Sidebar.md
Labels: Changes Requested, Review Required

#45 Add Política de juntas
  Política-de-Juntas.md
  _Sidebar.md
Labels: Requested Changes Fixed, Review Required

#28 Proceso de Identificación de Riesgos subido y corregido
  Proceso-de-identificación-de-riesgos.md
Labels: Changes Requested, Communication Required, Review Required

#29 Proceso de Seguimiento de Riesgos subido y corregido
  Proceso-de-monitoreo-de-riesgos.md
Labels: Changes Requested, Communication Required, Review Required

#47 Quitar títulos duplicados, arreglar sidenav
  Guía-para-agendar-eventos.md
  Proceso-para-Planificar.md
  _Sidebar.md
Labels: Review Required

#49 dir: Agregar tablas de directorios de archivos de cmmi
  Directorio-de-archivos-de-CMMI.md
  _Sidebar.md
Labels: Review Required

#52 Directorio de archivos del departamento
  Directorio-de-archivos-del-departamento.md
  _Sidebar.md
Labels: Approved

#50 Arreglar link roto de Política de Juntas
  _Sidebar.md
Labels: Requested Changes Fixed, Review Required

#53 Agregar Politica de WoW
  Politica-de-Nova-WoW.md
  _Sidebar.md
Labels: Review Required

#54 Agregar politica de comunicación
  Politica-de-Comunicacion.md
  _Sidebar.md
Labels: Review Required

#37 Política de Gestión de Métricas
  Política-de-gestión-de-métricas.md
Labels: Requested Changes Fixed, Review Required

#35 Update Proceso-de-gestion-de-metricas.md
  Proceso-de-gestion-de-metricas.md
  Proceso-de-gestión-de-métricas.md
Labels: Changes Requested

#61 dir: Agregar archivo de MonkeyType en andromeda
  Directorio-de-archivos-del-departamento.md
Labels: Review Required

#51 Corrección: Guía de uso de Clockify
  Guía de uso de Clockify.md
Labels: Changes Requested, Requested Changes Fixed

#62 Se modifico Hora del Depto
  Politica-de-Nova-WoW.md
Labels: Review Required

#48 Se corrigió el enlace al repositorio usado por Andrómeda
  Home.md
Labels: Changes Requested, Requested Changes Fixed

#71 Dir: Update dir matriz de riesgos
  Directorio-de-archivos-de-CMMI.md
Labels: Approved

#76 Eliminación de divulgación
  [PRO01]-Proceso-para-definir-un-proceso.md
Labels: Review Required

#80 Esta es la buena para el proceso de auditorías
  Proceso-de-auditorías.md
Labels: Review Required

#83 Politica de Configuration Control Board
  Politica-de-Configuration-Control-Board.md
  _Sidebar.md
Labels: Review Required

#79 Politica de líneas base
  Politica-de-lineas-base.md
  _Sidebar.md
Labels: Approved, bug

#87 Update Guía de institucionalización
  Guía-para-institucionalizar-procesos-guías-políticas.md
Labels: Review Required

#42 Add Proceso de Cierre de Iteracion
  Proceso-Cierre-de-Iteracion.md
  _Sidebar.md
Labels: Requested Changes Fixed, Review Required

#84 Politica/manejodedatos
  Politica-de-Manejo-de-Datos.md
  _Sidebar.md
Labels: Review Required

#64 Guía de Identificación de Métricas
  Guía-de-Identificación-de-Métricas.md
Labels: Changes Requested

#88 add politica de habilidades
  Politica-de-gestion-habilidades-y-conocimientos.md
  _Sidebar.md
Labels: Requested Changes Fixed, Review Required

#86 Cambiar política de CCB
  Politica-de-Configuration-Control-Board.md
Labels: Review Required

#82 Nuevo Proceso de Gestión de Historias de Usuario
  Proceso-de-gestión-de-historias-de-usuario.md
Labels: Changes Requested

#91 Guía del Entorno de Verificación
  Guía-de-entorno-de-verificación.md
Labels: Review Required

#66 Update Política-de-gestión-de-métricas.md
  Política-de-gestión-de-métricas.md
Labels: Changes Requested

#67 Política de elementos de la configuración
  Politica-de-elementos-de-la-configuracion.md
  _Sidebar.md
Labels: Review Required

#68 Proceso de Mejora de Procesos (PIP)
  Proceso-de-mejora-de-procesos.md
  _Sidebar.md
Labels: Review Required

#98 Guía del Ciclo de Vida del Proyecto
  Guía-de-ciclo-de-vida-del-proyecto.md
Labels: Review Required

#97 Guía de Determinación de Evaluación de Decisiones
  Guía-de-determinación-de-evaluación-de-decisiones.md
Labels: Review Required

#96 Cuestionario de Salud Discord Cheatsheet
  Cuestionario-de-Salud-Discord-Cheatsheet.md
Labels: Review Required

#69 Proceso de medidas correctivas
  Proceso-de-ejecución-de-medidas-correctivas.md
Labels: Requested Changes Fixed, Review Required

#95 Guía del Cuestionario de Salud
  Guía-del-Cuestionario-de-Salud.md
Labels: Review Required

#94 Update and rename Guía-para-las-juntas-de-seguimiento-personal-(JSP).…
  Guía-de-Juntas-de-Seguimiento-Personal-(JSP).md
  Guía-para-las-juntas-de-seguimiento-personal-(JSP).md
Labels: Review Required

#93 Update and rename Guía-para-las-juntas-de-desempeño.md to Guía-de-jun…
  Guía-de-juntas-de-desempeño.md
  Guía-para-las-juntas-de-desempeño.md
Labels: Review Required

#92 Proceso de Verificación de Productos
  Proceso-de-verificación-de-productos.md
Labels: Review Required

#73 update: Proceso de identificación de riesgos
  Proceso-de-identificación-de-riesgos.md
  _Sidebar.md
Labels: Requested Changes Fixed, Review Required

#65 Update Proceso-de-gestión-de-métricas.md
  Proceso-de-gestión-de-métricas.md
Labels: Changes Requested

#77 Update: Proceso de monitoreo de riesgos
  Proceso-de-monitoreo-de-riesgos.md
  _Sidebar.md
Labels: Review Required

#74 Proceso de reporte de estado
  Proceso-de-reporte-de-estado.md
  _Sidebar.md
Labels: Requested Changes Fixed

#78 Restructuración del proceso
  Proceso-para-institucionalizar-procesos-guías-y-políticas.md
Labels: Changes Requested

#56 Proceso/modificar linea base
  [PRO07]-Proceso-de-Modificación-de-baseline.md
  _Sidebar.md
Labels: Review Required

#100 Proceso Junta con el Cliente
  Proceso-para-junta-con-el-cliente.md
Labels: Review Required

#57 Actualización proceso planificación
  Proceso-para-Planificar.md
Labels: Requested Changes Fixed, Review Required

#103 Guía del Product Owner
  Guía-del-product-owner.md
Labels: Review Required

#111 Update: Proceso junta de cliente
  Proceso-para-junta-con-el-cliente.md
Labels: bug

#55 Add Procesos para planear iteraciones
  Proceso-de-inicio-de-iteración.md
  _Sidebar.md
Labels: Requested Changes Fixed, Review Required

#113 fix: Arreglar la referencia a la guía de versionado
  Proceso-de-modificacion-de-linea-base.md
Labels: Review Required, bug

#118 Update: Agregar a proceso de daily meeting medidas correctivas y matr…
  Proceso-de-Daily-Meeting.md
Labels: Review Required

#120 Update Guía-de-determinación-de-evaluación-de-decisiones.md
  Guía-de-determinación-de-evaluación-de-decisiones.md
Labels: Review Required

#122 Añadir milestones de las fases
  Guía-de-ciclo-de-vida-del-proyecto.md
Labels: Review Required

#114 fix table
  Proceso-para-junta-con-el-cliente.md
Labels: Review Required

#124 Update Proceso de Mejora de Procesos
  Proceso-de-mejora-de-procesos.md
Labels: Review Required

#128 Update _Sidebar.md
  _Sidebar.md
Labels: Review Required

#130 Update Guía-de-entorno-de-verificación.md
  Guía-de-entorno-de-verificación.md
Labels: Review Required

#127 Update Proceso-de-gestión-de-historias-de-usuario.md
  Proceso-de-gestión-de-historias-de-usuario.md
Labels: Review Required

#136 Update Proceso Auditorías CM + PPQA
  Guía-de-Team-Member.md
  Proceso-de-auditorías.md
Labels: Review Required

#137 Proceso de Gestión de Cambios a Historias de Usuario
  Proceso-de-gestión-de-historias-de-usuario.md
Labels: Review Required

#142 actualizacion proceso 24 sidebar
  _Sidebar.md
Labels: Review Required

#143 Proceso para definir el alcance
  Proceso-para-definir-el-alcance.md
Labels: Review Required

#144 Guia para estimar
  Guía-para-Estimar.md
  _Sidebar.md
Labels: Review Required

#150 Procesos Verificados y Validados
  Guía-de-resolución-de-conflictos.md
  Proceso-Cierre-de-Iteracion.md
  Proceso-de-Daily-Meeting.md
  Proceso-de-asignación-de-roles.md
  Proceso-de-auditorías.md
  Proceso-de-ejecución-de-medidas-correctivas.md
  Proceso-de-gestión-de-cambios-a-historias-de-usuario.md
  Proceso-de-gestión-de-historias-de-usuario.md
  Proceso-de-gestión-de-métricas.md
  Proceso-de-inicio-de-iteración.md
  Proceso-de-mejora-de-procesos.md
  Proceso-de-modificacion-de-linea-base.md
  Proceso-de-reporte-de-estado.md
  Proceso-de-toma-de-decisiones.md
  Proceso-de-verificación-de-código.md
  Proceso-para-institucionalizar-procesos-guías-y-políticas.md
  Proceso-para-junta-con-el-cliente.md
  Proceso-para-plan-de-Involucramiento-de-Stakeholders.md
  _Sidebar.md
Labels: Review Required

#145 Proceso de SCAMPI
  Proceso-de-SCAMPI.md
  _Sidebar.md
Labels: Review Required

#148 Update Proceso-de-toma-de-decisiones.md
  Proceso-de-toma-de-decisiones.md
Labels: Review Required

#139 Guia peticion cambio US
  Guia-de-peticion-cambio-de-historias-de-usuario.md
Labels: Review Required

#149 Refactor a proceso
  Proceso-para-generar-un-backlog.md
  _Sidebar.md
Labels: Review Required

#135 Guía de Identificación de Inconsistencias
  Guía-de-identificación-de-inconsistencias.md
Labels: Changes Requested, Review Required

#129 Update Proceso-de-inicio-de-iteración.md
  Proceso-de-inicio-de-iteración.md
Labels: Requested Changes Fixed, Review Required

#151 Update Proceso-de-toma-de-decisiones.md
  Proceso-de-toma-de-decisiones.md
Labels: Review Required

#153 Política de manejo de datos
  Política-de-Manejo-de-Datos.md
  _Sidebar.md
Labels: Review Required

#154 Correcciones Guías
  Guia-de -especificacion-requisitos.md
  Guía de uso de Clockify.md
  Guía-de-CMMI.md
  Guía-de-Identificación-de-Métricas.md
  Guía-de-Nova-Flow.md
  Guía-de-Team-Member.md
  Guía-de-asignación-de-roles.md
  Guía-de-ciclo-de-vida-del-proyecto.md
  Guía-de-denuncias.md
  Guía-de-determinación-de-evaluación-de-decisiones.md
  Guía-de-entorno-de-verificación.md
  Guía-de-identificación-de-inconsistencias.md
  Guía-de-identificación-de-riesgos.md
  Guía-de-juntas-de-desempeño.md
  Guía-de-juntas-de-seguimiento-personal.md
  Guía-de-manejo-de-configuración.md
  Guía-de-petición-de-cambios-a-historias-de-usuario.md
  Guía-de-resolución-de-conflictos.md
  Guía-de-versionado.md
  Guía-del-Cuestionario-de-Salud.md
  Guía-del-Program-Manager.md
  Guía-del-Team-Leader.md
  Guía-del-product-owner.md
  Guía-para-Estimar.md
  Guía-para-agendar-eventos.md
  Guía-para-definir-un-WBS.md
  Guía-para-identificar-procesos-guías-políticas.md
  Guía-para-institucionalizar-procesos-guías-políticas.md
  Proceso-Cierre-de-Iteracion.md
  Proceso-de-Daily-Meeting.md
  Proceso-de-SCAMPI.md
  Proceso-de-asignación-de-roles.md
  Proceso-de-auditorías.md
  Proceso-de-ejecución-de-medidas-correctivas.md
  Proceso-de-gestión-de-cambios-a-historias-de-usuario.md
  Proceso-de-gestión-de-historias-de-usuario.md
  Proceso-de-gestión-de-métricas.md
  Proceso-de-gestión-de-riesgos.md
  Proceso-de-inicio-de-iteración.md
  Proceso-de-mejora-de-procesos.md
  Proceso-de-modificacion-de-linea-base.md
  Proceso-de-reporte-de-estado.md
  Proceso-de-toma-de-decisiones.md
  Proceso-de-verificación-de-código.md
  Proceso-para-definir-el-alcance.md
  Proceso-para-definir-un-proceso.md
  Proceso-para-generar-un-backlog.md
  Proceso-para-institucionalizar-procesos-guías-y-políticas.md
  Proceso-para-junta-con-el-cliente.md
  Proceso-para-plan-de-Involucramiento-de-Stakeholders.md
  _Sidebar.md
Labels: Review Required

#156 Actualizar directorios de Andrómeda
  Directorio-de-archivos-del-departamento.md
Labels: Review Required

#155 Actualización a la POL
  Politica-de-Comunicacion.md
  Política-de-Comunicación.md
  _Sidebar.md
Labels: Review Required
